export const content = [
	{
		title: "Languages",
		desc: "Programming, markup, and style sheet languages.",
		contents: [
			"Arduino",
			"C",
			"C++",
			"CSS",
			"Dart",
			"GraphQL",
			"Go",
			"HTML",
			"Java",
			"JavaScript",
			"MATLAB",
			"Python",
			"PHP",
			"SASS",
			"SQL",
			"TypeScript",
			"VHDL",
		],
	},
	{
		title: "Frameworks and Libraries",
		desc: "Major frameworks and libraries.",
		contents: [
			"Angular.js",
			"Django",
			"Electron.js",
			"Express.js",
			"FalconPy",
			"Flutter",
			"Gin Gonic",
			"Go Fiber",
			"Laravel",
			"Next.js",
			"Nuxt.js",
			"pandas",
			"React.js",
			"React Native",
			"Spring Boot",
			"Sapper",
			"Svelte",
			"TensorFlow",
			"Vue.js",
		],
	},
	{
		title: "Tools",
		desc: "Other tools.",
		contents: [
			"Adobe Illustrator",
			"Adobe Photoshop",
			"Adobe XD",
			"Anaconda",
			"Android Studio",
			"Amazon Web Services",
			"CPanel",
			"DigitalOcean",
			"Docker",
			"Figma",
			"Google Cloud Platform",
			"Git",
			"Jenkins",
			"Jupyter Notebook",
			"Kubernetes",
			"Linux",
			"LTSpice",
			"MS Office",
			"Postman",
			"PuTTY",
			"Selenium",
			"Tableau",
			"Visual Studio Code",
			"Visual Studio",
		],
	},
];
